# This is a basic workflow to help you get started with Actions
name: TEST
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs: 
        id:
          description: 'id identifier'
          required: false
        param2:
          description: 'param1 identifier'
          required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
            image: docker.io/middesb/gh_actions_app:0.0.2
            credentials:
               username: middesb
               password: ${{  secrets.TEST_DOCKER_PWD }}

    steps:
      - uses: actions/checkout@v3
      - name: download image from docker
        shell: bash
        run: |
                 # Whatever commands you want to run here using the container with your
                 # new Docker image at ghcr.io!
                 echo "--This is running in my custom Docker image-
                 docker save  -o midde/image.tar middesb/argo_actions_app:0.0.1 
                 ls midde -ltr
