# This is a basic workflow to help you get started with Actions
name: TEST
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs: 
        id:
          description: 'id identifier'
          required: false
        param2:
          description: 'param1 identifier'
          required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64


    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: middesb
          password: ${{ secrets.TEST_DOCKER_PWD }}
      - name: docker pull and save and upload artifact
      - run: mkdir ecr_artifact 
      - run: docker pull  middesb/test_repository:v1
      - run: docker save  -o ecr_artifact/image.tar middesb/test_repository:v1 
      - run: ls -ltr ecr_artifact

      - uses: actions/upload-artifact@v3
        with:
           name: tar_image_${{github.run_id}}
           path: ecr_artifact/image.tar
          
           
 
