# This is a basic workflow to help you get started with Actions
name: TEST
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs: 
        id:
          description: 'id identifier'
          required: false
        param2:
          description: 'param1 identifier'
          required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    container:
            image: docker.io/middesb/test_repository:v1
            credentials:
               username: middesb
               password: ${{  secrets.TEST_DOCKER_PWD }}

    steps:
      - uses: actions/checkout@v3
      - name: create artifact directory
        run: mkdir ecr_artifact
      - name: save image from docker
        run: docker save  -o ecr_artifact/image.tar middesb/test_repository:v1 
      - name: list dir
        run: ls -ltr ecr_artifact
